"""Generates a `catalog/<slug>.py` module's source text from a flat list of
ControlInfo entries, in the same hand-written style as ddj_xp2.py/xdj_xz.py.
Used by gui/controller_setup.py's export step, kept Qt-free here so it's
independently testable and reusable outside the GUI."""

from __future__ import annotations

from seratomidiconf.catalog._registry import ControlInfo, ControllerDefinition


def find_trigger_conflicts(entries: list[ControlInfo]) -> list[str]:
    """A draft is unstable if the same raw (channel, note_or_cc, data1) trigger
    is claimed by two rows with a different (section, name) — i.e. the same
    physical press would resolve to two different answers from catalog.lookup()
    once exported, so only one could ever actually be correct. This can't happen
    through learning or XML import (gui/controller_setup.py's _maybe_add_row
    dedups on this exact key before adding a row) but can arise from hand-editing
    a row's Channel(s)/Type/Data1 cell into colliding with another row. Two rows
    that agree on (section, name) but differ only by channel are not a conflict —
    that's the normal case merge_by_channel folds together."""
    by_key: dict[tuple[str, str, str], list[ControlInfo]] = {}
    for entry in entries:
        for channel in entry.channels:
            by_key.setdefault((channel, entry.note_or_cc, entry.data1), []).append(entry)

    conflicts: list[str] = []
    for (channel, kind, data1), group in by_key.items():
        distinct_labels = sorted({(entry.section, entry.name) for entry in group})
        if len(distinct_labels) <= 1:
            continue
        labels = ", ".join(f"{section!r}/{name!r}" for section, name in distinct_labels)
        conflicts.append(
            f"Trigger (channel={channel}, type={kind}, data1={data1}) is claimed by "
            f"{len(distinct_labels)} different rows ({labels}) — only one can be correct."
        )
    return conflicts


def merge_by_channel(entries: list[ControlInfo]) -> list[ControlInfo]:
    """Folds rows that share (section, name, note_or_cc, data1) and differ
    only by channel into one ControlInfo with a combined channel tuple —
    reproduces the hand-written modules' "one row, multiple channels" shape
    for the common case (the same button learned once per deck). First-seen
    order is preserved for both entry position and channel order."""
    groups: dict[tuple[str, str, str, str], list[str]] = {}
    order: list[tuple[str, str, str, str]] = []
    controller_by_key: dict[tuple[str, str, str, str], str] = {}
    for entry in entries:
        key = (entry.section, entry.name, entry.note_or_cc, entry.data1)
        if key not in groups:
            groups[key] = []
            order.append(key)
            controller_by_key[key] = entry.controller
        for channel in entry.channels:
            if channel not in groups[key]:
                groups[key].append(channel)
    return [
        ControlInfo(controller_by_key[key], key[0], key[1], key[2], tuple(groups[key]), key[3]) for key in order
    ]


def infer_section_order(entries: list[ControlInfo]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(entry.section for entry in entries))


def build_definition(controller_name: str, entries: list[ControlInfo]) -> ControllerDefinition:
    """Turns a (possibly unmerged) draft into a ControllerDefinition ready to
    register — the semantic source of truth generate_module_source's text
    mirrors, and what gui/controller_setup.py's "Apply now" action registers
    directly into the live registry (in-memory, no file write). Always
    pad_lookup=None/pad_count=0, see generate_module_source."""
    merged = merge_by_channel(entries)
    return ControllerDefinition(
        name=controller_name,
        static_entries=merged,
        pad_lookup=None,
        pad_count=0,
        pad_columns=4,
        section_order=infer_section_order(merged),
    )


def _format_channels(channels: tuple[str, ...]) -> str:
    if len(channels) == 1:
        return f"({channels[0]!r},)"
    return "(" + ", ".join(repr(c) for c in channels) + ")"


def _format_entry(entry: ControlInfo) -> str:
    return (
        f"    ControlInfo({entry.controller!r}, {entry.section!r}, {entry.name!r}, "
        f"{entry.note_or_cc!r}, {_format_channels(entry.channels)}, {entry.data1!r}),"
    )


def generate_module_source(controller_name: str, entries: list[ControlInfo]) -> str:
    """entries should already be merged (see merge_by_channel) and belong to
    controller_name. Always emits pad_lookup=None/pad_count=0 — every learned
    or imported control becomes a flat static entry; inferring a compact
    pad-grid formula from captured data is out of scope for this generator."""
    section_order = infer_section_order(entries)
    lines = [
        f'"""{controller_name} controller definition, generated by the Controller Setup wizard',
        "(learned from live MIDI input and/or imported from an existing Serato XML config).",
        "Verify against the device's manual if one becomes available. See catalog/__init__.py",
        'for scope notes (discrete press/toggle controls only) shared across all controllers."""',
        "",
        "from __future__ import annotations",
        "",
        "from seratomidiconf.catalog._registry import ControlInfo, ControllerDefinition, register",
        "",
        "_STATIC: list[ControlInfo] = [",
    ]
    lines.extend(_format_entry(entry) for entry in entries)
    lines.append("]")
    lines.append("")
    lines.append("")
    lines.append("register(")
    lines.append("    ControllerDefinition(")
    lines.append(f"        name={controller_name!r},")
    lines.append("        static_entries=_STATIC,")
    lines.append("        pad_lookup=None,")
    lines.append("        pad_count=0,")
    lines.append("        pad_columns=4,")
    lines.append(f"        section_order={section_order!r},")
    lines.append("    )")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


__all__ = [
    "build_definition",
    "find_trigger_conflicts",
    "generate_module_source",
    "infer_section_order",
    "merge_by_channel",
]
