"""Package a Controller Setup draft as a community-catalog submission and turn
it into a pre-filled GitHub "new issue" URL.

Deliberately the smallest thing that works (issue #17's minimal option): no
endpoint, no auth, no moderation pipeline — the app opens a pre-filled issue
in the user's browser and puts the full JSON payload on the clipboard. The
transport/format/moderation/dedup questions in the issue are left for when a
dedicated community-profile repo exists; until then submissions land as
labelled issues on the app's own repo.

Qt-free on purpose so the payload/body/URL construction is unit-testable
without a QApplication; the GUI side (clipboard + open URL) lives in
gui/controller_setup.py.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from urllib.parse import quote

from djmidi.catalog._registry import ControllerDefinition

# Interim submission target. There is no separate community-profile repo yet
# (see issue #17's open questions), so submissions are labelled issues on the
# app's own repository.
COMMUNITY_REPO = "guillain/DJ-MIDI-Studio"
SUBMISSION_LABEL = "controller-submission"
SUBMISSION_SCHEMA = "controller-submission/1"

# GitHub accepts long querystrings but browsers/proxies get unreliable past a
# few KB; above this the JSON goes to the clipboard instead of the URL body.
_MAX_INLINE_URL_LENGTH = 6000


@dataclass(frozen=True)
class SubmissionMetadata:
    """Contributor-provided context for a submitted profile. Every field is
    optional — an empty submission still carries the trigger data."""

    contributor: str = ""
    target_hardware: str = ""
    firmware: str = ""
    source: str = ""  # "learned", "xml-import", "mixed", "manual", ...
    notes: str = ""


def summarise_source(sources: list[str]) -> str:
    """Collapse Controller Setup's per-row source tags into one label."""
    kinds = {s for s in sources if s}
    if not kinds:
        return ""
    if len(kinds) == 1:
        return next(iter(kinds))
    return "mixed (" + ", ".join(sorted(kinds)) + ")"


def build_submission_payload(
    definition: ControllerDefinition,
    metadata: SubmissionMetadata,
    *,
    generated_by: str = "DJ MIDI Studio",
) -> dict:
    """A versioned, self-contained dict describing the submitted controller.

    Reference images are intentionally excluded — only their filename is kept
    for context (the image file itself is the contributor's responsibility and
    is not redistributed through this path).
    """
    return {
        "schema": SUBMISSION_SCHEMA,
        "generated_by": generated_by,
        "controller_name": definition.name,
        "section_order": list(definition.section_order),
        "reference_image": definition.reference_image or "",
        "static_entries": [
            {
                "section": entry.section,
                "name": entry.name,
                "note_or_cc": entry.note_or_cc,
                "channels": list(entry.channels),
                "data1": entry.data1,
            }
            for entry in definition.static_entries
        ],
        "contributor": metadata.contributor,
        "target_hardware": metadata.target_hardware,
        "firmware": metadata.firmware,
        "source": metadata.source,
        "notes": metadata.notes,
    }


def payload_json(payload: dict) -> str:
    return json.dumps(payload, indent=2, sort_keys=True)


def submission_issue_title(payload: dict) -> str:
    return f"[controller submission] {payload.get('controller_name') or 'Unnamed controller'}"


def submission_issue_body(payload: dict, *, inline_json: bool) -> str:
    """Markdown body for the pre-filled issue. When ``inline_json`` is False a
    placeholder replaces the payload and the app is expected to have put the
    JSON on the clipboard for the contributor to paste."""
    entry_count = len(payload.get("static_entries", []))
    rows = [
        ("Controller name", payload.get("controller_name") or "_(unset)_"),
        ("Static entries", str(entry_count)),
        ("Contributor", payload.get("contributor") or "_(not given)_"),
        ("Target hardware", payload.get("target_hardware") or "_(not given)_"),
        ("Firmware", payload.get("firmware") or "_(not given)_"),
        ("Capture source", payload.get("source") or "_(not given)_"),
        ("Generated by", payload.get("generated_by") or ""),
    ]
    lines = [
        "Submitted from **DJ MIDI Studio → Controller Setup**.",
        "",
        "| Field | Value |",
        "| --- | --- |",
    ]
    lines += [f"| {label} | {value} |" for label, value in rows]
    notes = payload.get("notes")
    if notes:
        lines += ["", "**Notes**", "", notes]
    lines += [
        "",
        "### Profile data",
        "",
    ]
    if inline_json:
        lines += ["```json", payload_json(payload), "```"]
    else:
        lines += [
            (
                "<!-- The profile JSON was copied to your clipboard by the app — "
                "paste it between the fences below. -->"
            ),
            "```json",
            "",
            "```",
        ]
    lines += [
        "",
        "---",
        "",
        (
            "By submitting you confirm the trigger data and control names may be "
            "redistributed as part of the project's built-in catalog. Do not paste "
            "copyrighted material; reference images are not part of this submission."
        ),
    ]
    return "\n".join(lines)


def submission_issue_url(payload: dict, *, repo: str = COMMUNITY_REPO) -> tuple[str, bool]:
    """Return ``(url, json_was_inlined)`` for a GitHub "new issue" link.

    Tries to inline the JSON in the URL; if that makes the URL too long,
    rebuilds the body with a paste placeholder and returns ``False`` so the
    caller knows to rely on the clipboard.
    """
    base = f"https://github.com/{repo}/issues/new"
    title = submission_issue_title(payload)

    def _url(body: str) -> str:
        return (
            f"{base}?labels={quote(SUBMISSION_LABEL)}"
            f"&title={quote(title)}&body={quote(body)}"
        )

    inline_url = _url(submission_issue_body(payload, inline_json=True))
    if len(inline_url) <= _MAX_INLINE_URL_LENGTH:
        return inline_url, True
    return _url(submission_issue_body(payload, inline_json=False)), False


__all__ = [
    "COMMUNITY_REPO",
    "SUBMISSION_LABEL",
    "SUBMISSION_SCHEMA",
    "SubmissionMetadata",
    "build_submission_payload",
    "payload_json",
    "submission_issue_body",
    "submission_issue_title",
    "submission_issue_url",
    "summarise_source",
]
